version: '3.8'

services:
  vps-landing:
    container_name: vps-landing
    image: nginx:alpine
    restart: always
    ports:
      - "9095:80"
    volumes:
      - ./site-content:/usr/share/nginx/html:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
